### PR TITLE
Permission and Dependency Fixes

### PR DESCRIPTION
**Pull request by lmy441900**
This PR:

- adds executable permission to `manage.py` and `start.sh`
- upgrades all dependencies to fix security vulnerabilities as well as keep up-to-date

I've tested with Python 3 venv (without Docker) and seems working.

### CODE REVIEW

**Comment by lmy441900** [comment]
Also @mchobbylong in https://github.com/UICHCC/uicCourse/pull/68#pullrequestreview-802667018 mentioned a missing `EXPOSE 5002` in Dockerfile, does this affect accessibility? If so, better adding this in this PR.

**Comment by ecwu** [comment]
Changes in `requirements.txt` file LGTM.

**Comment by ecwu** [comment]
Oops, accidentally closed the PR, reopen.

**Review by ecwu — APPROVED** [review]

**Review by mchobbylong — APPROVED** [review]
LGTM.

**Pull request merged**
